apiVersion: v1
kind: Service
metadata:
  name: simple-webserver
  labels:
    app: simple-webserver
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8082
  selector:
    app: simple-webserver
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver
  labels:
    app: simple-webserver
spec:
  selector:
    matchLabels:
      app: simple-webserver
  template:
    metadata:
      labels:
        app: simple-webserver
        tier: frontend
    spec:
      containers:
      - image: kannanv/webserver:0.1
        name: simple-webserver
        command: ["app"]
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: simple-webserver
  name: simple-webserver
  namespace: default
spec:
  backend:
    serviceName: simple-webserver
    servicePort: 8082

